"""
Artifact Archiver for Bio-Plausible Experiments

Handles saving model checkpoints, configurations, and logs to a structured
archive format (ZIP) for reproducibility and industrial-grade tracking.
"""

import json
import logging
import shutil
import zipfile
from pathlib import Path
from typing import Any, Dict, Optional

import torch

logger = logging.getLogger("Archiver")

ARTIFACTS_DIR = Path("artifacts")


class ExperimentArchiver:
    """
    Manages the creation and storage of experiment artifacts.
    """

    def __init__(self, base_dir: Path = ARTIFACTS_DIR):
        self.base_dir = base_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def archive_trial(
        self,
        trial_id: int,
        model: torch.nn.Module,
        config: Dict[str, Any],
        metrics: Dict[str, Any],
        extra_files: Optional[Dict[str, str]] = None,
    ) -> Optional[str]:
        """
        Creates a ZIP archive for a specific trial.

        Args:
            trial_id: Unique trial ID.
            model: The PyTorch model to save.
            config: Configuration dictionary.
            metrics: Final metrics dictionary.
            extra_files: Optional dictionary mapping filename -> content (str).

        Returns:
            Path to the created ZIP file, or None if failed.
        """
        try:
            trial_name = f"trial_{trial_id}_{config.get('model', 'unknown')}"
            trial_dir = self.base_dir / trial_name
            trial_dir.mkdir(exist_ok=True)

            # 1. Save Model Checkpoint
            checkpoint_path = trial_dir / "model.pt"
            torch.save(model.state_dict(), checkpoint_path)

            # 2. Save Config
            with open(trial_dir / "config.json", "w") as f:
                json.dump(config, f, indent=2)

            # 3. Save Metrics
            with open(trial_dir / "metrics.json", "w") as f:
                json.dump(metrics, f, indent=2)

            # 4. Generate Reproducibility Script
            repro_script = self._generate_reproduction_script(
                config.get("model", "unknown"), config, metrics
            )
            with open(trial_dir / "reproduce.py", "w") as f:
                f.write(repro_script)

            # 5. Extra Files (e.g., reproduction script snippet)
            if extra_files:
                for fname, content in extra_files.items():
                    with open(trial_dir / fname, "w") as f:
                        f.write(content)

            # 6. Create ZIP
            zip_path = self.base_dir / f"{trial_name}.zip"
            with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
                for file in trial_dir.iterdir():
                    zf.write(file, file.name)

            # Cleanup directory
            shutil.rmtree(trial_dir)

            logger.info(f"Archived trial {trial_id} to {zip_path}")
            return str(zip_path)

        except Exception as e:
            logger.error(f"Failed to archive trial {trial_id}: {e}")
            return None

    def _generate_reproduction_script(
        self, model_name: str, config: Dict[str, Any], metrics: Dict[str, Any]
    ) -> str:
        """
        Generates a standalone Python script to reproduce this specific trial.
        """
        # Use repr() to ensure Python-compatible boolean/None values (True/False/None)
        config_repr = repr(config)

        script = f'''"""
Standalone Reproduction Script
Generated by AutoScientist
Model: {model_name}
Original Accuracy: {metrics.get("accuracy", 0.0):.4f}
"""

import torch
import json
from bioplausible.models.registry import get_model_spec
from bioplausible.models.factory import create_model
from bioplausible.training.supervised import SupervisedTrainer
from bioplausible.hyperopt.tasks import create_task

def reproduce():
    # 1. Configuration
    config = {config_repr}

    print(f"Reproducing model: {{config['model']}}")
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # 2. Setup Task
    task_name = config.get("task", "mnist")
    print(f"Loading task: {{task_name}}...")
    task = create_task(task_name, device=device, quick_mode=False)
    task.setup()

    # 3. Create Model
    print("Creating model...")
    spec = get_model_spec(config["model"])
    model = create_model(
        spec=spec,
        input_dim=task.input_dim,
        output_dim=task.output_dim,
        hidden_dim=config.get("hidden_dim", 128),
        num_layers=config.get("num_layers", 4),
        device=device,
        task_type=task.task_type
    )

    # Apply params
    if "beta" in config and hasattr(model, "beta"):
        model.beta = config["beta"]

    # 4. Train
    print("Starting training...")
    trainer = task.create_trainer(
        model,
        lr=config.get("lr", 0.001),
        steps=config.get("steps", 20),
        batches_per_epoch=200,
        eval_batches=50
    )

    epochs = config.get("epochs", 5)
    for epoch in range(epochs):
        metrics = trainer.train_epoch()
        acc = metrics.get('accuracy', 0.0)
        loss = metrics['loss']
        print(
            f"Epoch {{epoch+1}}/{{epochs}}: Acc={{acc:.4f}} Loss={{loss:.4f}}"
        )

if __name__ == "__main__":
    reproduce()
'''
        return script
