"""
AutoScientist: The Autonomous Discovery Agent.

This module implements the core logic for the continuous experiment runner.
It manages the experiment lifecycle:
1. State Analysis: What have we learned so far?
2. Strategy: What should we do next? (Smoke -> Shallow -> Standard -> Deep)
3. Execution: Run the experiment.
4. Learning: Update the knowledge base.
"""

import time
import signal
import sys
import random
import optuna
import logging
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass
from pathlib import Path

from bioplausible.models.registry import MODEL_REGISTRY, ModelSpec
from bioplausible.hyperopt import create_optuna_space, PatientLevel, get_evaluation_config
from bioplausible.hyperopt.runner import run_single_trial_task
from bioplausible.hyperopt.storage import HyperoptStorage

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("scientist.log"),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger("AutoScientist")

DB_PATH = "bioplausible.db"

@dataclass
class ExperimentTask:
    """Represents a single planned experiment."""
    model_name: str
    task_name: str
    tier: PatientLevel
    study_name: str
    priority: float  # Higher is better


class ExperimentState:
    """
    Analyzes the current state of research by querying the database.
    """
    def __init__(self, db_path: str):
        self.db_path = db_path
        self.storage = HyperoptStorage(db_path)

    def get_progress(self) -> Dict[str, Dict[str, Dict[str, Any]]]:
        """
        Returns a nested dictionary:
        { model_name: { task_name: { tier_name: { 'count': int, 'best_acc': float } } } }
        """
        # We use HyperoptStorage to get completed trials
        # Note: We need to parse user_attrs from config or Optuna.
        # Since HyperoptStorage stores 'config_json', we rely on that.
        # However, earlier we noted config might not have tier/task.
        # We will assume for *new* runs generated by AutoScientist, we put them there.
        # For legacy runs, we might miss them.

        trials = self.storage.get_all_trials()
        progress = {}

        for t in trials:
            if t.status != "completed":
                continue

            model = t.model_name
            # Try to get task/tier from config first
            task = t.config.get("task")
            tier_val = t.config.get("tier")

            # If missing, skip (or assume defaults if we wanted to support legacy)
            if not task or not tier_val:
                continue

            if model not in progress: progress[model] = {}
            if task not in progress[model]: progress[model][task] = {}
            if tier_val not in progress[model][task]:
                progress[model][task][tier_val] = {'count': 0, 'best_acc': -1.0}

            entry = progress[model][task][tier_val]
            entry['count'] += 1
            if t.accuracy > entry['best_acc']:
                entry['best_acc'] = t.accuracy

        return progress

    def get_optuna_study(self, study_name: str):
        """Load or create an Optuna study."""
        return optuna.create_study(
            study_name=study_name,
            storage=f"sqlite:///{self.db_path}",
            direction="maximize",
            load_if_exists=True,
            sampler=optuna.samplers.TPESampler()
        )


class ScientistStrategy:
    """
    The Brains. Decides what to run next.
    """

    # Success Criteria (vs Random/Baseline)
    CRITERIA = {
        PatientLevel.SMOKE: lambda acc: acc > 0.15, # Better than random (10 classes)
        PatientLevel.SHALLOW: lambda acc: acc > 0.40, # Showing promise
        PatientLevel.STANDARD: lambda acc: acc > 0.60, # Strong candidate
    }

    TASKS = ["vision", "lm", "rl"]

    def __init__(self, state: ExperimentState):
        self.state = state

    def plan_next(self) -> Optional[ExperimentTask]:
        """
        Scans all possibilities and returns the highest priority experiment.
        """
        progress = self.state.get_progress()
        candidates = []

        for spec in MODEL_REGISTRY:
            # Filter compatible tasks
            tasks = spec.task_compat if spec.task_compat else self.TASKS

            for task in tasks:
                # Check tiers in order

                # 1. SMOKE
                smoke_stats = self._get_stats(progress, spec.name, task, PatientLevel.SMOKE)
                if smoke_stats['count'] < 3: # Need at least 3 smoke tests
                    # Priority: High for never run, Med for < 3
                    p = 100.0 if smoke_stats['count'] == 0 else 80.0
                    candidates.append(self._make_task(spec.name, task, PatientLevel.SMOKE, p))
                    continue # Focus on filling smoke first

                # If Smoke failed, don't proceed (Implicit Pruning)
                if not self.CRITERIA[PatientLevel.SMOKE](smoke_stats['best_acc']):
                    # Maybe retry occasionally? Small prob
                    if random.random() < 0.05:
                        candidates.append(self._make_task(spec.name, task, PatientLevel.SMOKE, 10.0))
                    continue

                # 2. SHALLOW
                shallow_stats = self._get_stats(progress, spec.name, task, PatientLevel.SHALLOW)
                if shallow_stats['count'] < 10:
                    # Promoted from Smoke!
                    p = 60.0 + (smoke_stats['best_acc'] * 20.0) # Bonus for good smoke perf
                    candidates.append(self._make_task(spec.name, task, PatientLevel.SHALLOW, p))
                    continue

                if not self.CRITERIA[PatientLevel.SHALLOW](shallow_stats['best_acc']):
                     continue

                # 3. STANDARD
                std_stats = self._get_stats(progress, spec.name, task, PatientLevel.STANDARD)
                if std_stats['count'] < 20:
                    p = 40.0 + (shallow_stats['best_acc'] * 30.0)
                    candidates.append(self._make_task(spec.name, task, PatientLevel.STANDARD, p))
                    continue

                if not self.CRITERIA[PatientLevel.STANDARD](std_stats['best_acc']):
                     continue

                # 4. DEEP
                deep_stats = self._get_stats(progress, spec.name, task, PatientLevel.DEEP)
                if deep_stats['count'] < 5:
                    p = 20.0 + (std_stats['best_acc'] * 50.0)
                    candidates.append(self._make_task(spec.name, task, PatientLevel.DEEP, p))

        if not candidates:
            return None

        # Sort by priority and pick top
        # Add some randomness to avoid determinism loops
        candidates.sort(key=lambda x: x.priority + random.uniform(0, 5), reverse=True)
        return candidates[0]

    def _get_stats(self, progress, model, task, tier):
        try:
            return progress[model][task][tier.value]
        except KeyError:
            return {'count': 0, 'best_acc': 0.0}

    def _make_task(self, model, task, tier, priority):
        return ExperimentTask(
            model_name=model,
            task_name=task,
            tier=tier,
            study_name=f"{model}_{task}_{tier.value}",
            priority=priority
        )


class AutoScientist:
    """
    The main loop.
    """
    def __init__(self):
        self.state = ExperimentState(DB_PATH)
        self.strategy = ScientistStrategy(self.state)
        self.running = True

        # Handle Ctrl+C
        signal.signal(signal.SIGINT, self._signal_handler)

    def _signal_handler(self, sig, frame):
        logger.info("Interrupt received. Finishing current trial...")
        self.running = False

    def run(self):
        logger.info("AutoScientist initialized. Starting continuous discovery...")

        while self.running:
            # 1. Plan
            task = self.strategy.plan_next()

            if not task:
                logger.info("No viable experiments found. Sleeping 60s...")
                time.sleep(60)
                continue

            logger.info(f"Starting Trial: {task.model_name} | {task.task_name} | {task.tier.name} (Priority: {task.priority:.1f})")

            # 2. Prepare Config
            try:
                # Load Optuna Study
                study = self.state.get_optuna_study(task.study_name)

                # Ask for params
                trial = study.ask()

                # Generate Config
                config = create_optuna_space(trial, task.model_name)

                # Inject Tier Config
                tier_config = get_evaluation_config(task.tier)
                config["epochs"] = tier_config.epochs
                config["batch_size"] = tier_config.batch_size

                # IMPORTANT: Inject Metadata for Analysis
                config["tier"] = task.tier.value
                config["task"] = task.task_name
                config["model"] = task.model_name

                # 3. Execute
                logger.info(f"  > Trial {trial.number}: Epochs={config['epochs']}, Batch={config['batch_size']}")

                # We use quick_mode=True for SMOKE to enforce speed, else False
                quick = (task.tier == PatientLevel.SMOKE)

                metrics = run_single_trial_task(
                    task=task.task_name,
                    model_name=task.model_name,
                    config=config,
                    storage_path=DB_PATH,
                    job_id=trial.number,
                    quick_mode=quick
                )

                # 4. Report
                if metrics:
                    acc = metrics.get("accuracy", 0.0)
                    loss = metrics.get("loss", float("inf"))
                    logger.info(f"  > Result: Accuracy={acc:.2%}, Loss={loss:.4f}")

                    # Tell Optuna (maximize accuracy)
                    study.tell(trial, acc)
                else:
                    logger.warning("  > Trial failed (no metrics returned).")
                    study.tell(trial, 0.0, state=optuna.trial.TrialState.FAIL)

            except Exception as e:
                logger.error(f"Error executing trial: {e}", exc_info=True)
                time.sleep(5) # Cooldown on error

            # Sleep briefly to allow Ctrl+C to catch
            time.sleep(1)

        logger.info("AutoScientist stopped safely.")

if __name__ == "__main__":
    scientist = AutoScientist()
    scientist.run()
